### ISSUE TITLE
Schreiben der Starting 6 ins Config-File

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#11]
Die Buttons Linie 1-4 bei der Starting6 werden nicht korrekt ins Config-File geschrieben. Manuell funktioniert.

**Comment by biscmar** [comment]
Kann ich nicht reproduzieren. Bei mir scheint alles zu funktionieren. Kannst du das bitte nochmals testen?

**Comment by patmu** [comment]
Korrekt, funktioniert jetzt.
