### ISSUE TITLE
Spieldaten laden / Löschen Textfelder

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#14]
Beim Laden vonneuen Spieldaten werden die Textboxen der "Starting6 Manuell" nicht gelöscht.

**Comment by patmu** [comment]
Dies gilt nicht nur für die Starting 6. Ich habe festgestellt, dass dies auch für andere Textfelder wie Schiedsrichter, Kommentatoren, etc. gilt.

Damit wir nicht inkonsistente Daten erhalten, müssten vor dem Spiel laden alle Controls zurück gesetzt werden.

**Comment by biscmar** [comment]
Ist angepasst. Beim laden eines Spiels werden jetzt als erstes alle Felder zurückgesetzt.
