### ISSUE TITLE
Dialog "Es sind Fehler aufgetreten"

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#15]
st fraglich ob dies Sinn macht. Es sind eigentlich alles optionale Angaben, insb. in den unteren Ligen.

Oder sollen einfach nur Warnungen ausgegeben werden, das Herunterladen des Files ist aber trotzdem möglich?

**Comment by biscmar** [comment]
Ich gebe diese momentan als Fehler aus, weil diese Werte im PHP benötigt werden. Ich werde das in dem Fall weiter optimieren.

**Comment by biscmar** [comment]
Validierung verbessert. Es wird jetzt zwischen Warnung und Fehler unterschieden.

**Comment by patmu** [comment]
Ich denke, dass dies im Zusammenhang mit der Aufstellung noch nicht ideal gelöst ist.

In den unteren Ligen wird es wohl so sein, dass keine Aufstellungen der Teams verfügbar sind. Nur in der NLA Herren werden die Teams diese neu 1h vor Spielbeginn abgeben müssen.

So wie es jetzt gelöst ist, ist die Aufstellung zwingend. Klar kann man eine Fake-Aufstellung eingeben, ich finde diesen Schritt aber unnötigt, wenn man eh nicht die richtigen Daten hat.

Besser:
- Die Aufstellung auch optional machen -> Warnung
- Export ins Textfile immer alle Spieler, welche die API zurück gibt.

**Comment by biscmar** [comment]
Aso du siehst die unteren Ligen bereits als konkreten Use Case für die aktuelle Version? Dann bin ich aber der Meinung, dass wir das grundsätzlich im TCUconfig berücksichtigen müssen... 

Im Moment gehe ich davon aus, dass die API eine Spielerliste retour liefert. Ich nehme an, dies dürfen wir bei den unteren Ligen nicht als gegeben betrachten, oder? In diesem Fall haben sie aktuell keine andere Möglichkeit, als ihre Aufstellungen direkt ins .txt File schreiben, was wir ja eigentlich mit TCUconfig verhindern möchten :)

Die Validierung, dass eine Aufstellung vorhanden sein muss, finde ich eigentlich schon in Ordnung. Die sauberste Lösung wäre aus meiner Sicht, dass eine "manuelle Aufstellung" erfasst werden kann. Dann spielt es keine Rolle mehr, ob OSB oder nicht. Mir war nur nicht bewusst, dass dies bereits ein konkreter Use Case ist.

**Comment by patmu** [comment]
Im Moment habe ich vorallem an die Herren NLB gedacht (Thurgau, Basel). Dort ist das Abgeben der Aufstellung/Linien nicht obligatorisch, der OSB aber in Betrieb.

Somit haben wir drei Fälle:
1) Spiel mit OSB inkl. Spielerdaten und Pflicht zur Abgabe der Aufstellung (Herren NLA)
2) Spiel mit OSB inkl. Spielerdaten und ohne Pflicht zur Abgabe der Aufstellung (Herren NLB/Damen NLA); wird künftig der am meisten auftretende Fall sein.
3) Spiel ohne OSB (tiefere Ligen); abnehmend.

Der OSB soll aber später überall eingesetzt werden, sodass wir davon ausgehen immer Spielerdaten zu haben.  Was wir aber nicht immer haben ist die konkrete Aufstellung.

Insofern sehe ich 3) nur als vorübergehenden Use Case. Aktuell sind keine Anfragen da, dass andere als die oben genannten Ligen streamen wollen. Insofern würde ich im Moment ein manuelles Erfassen von Spielerdaten nicht als Anforderung sehen (wobei das dann auch das Problem der fehlenden Aufstellung nicht löst).

Prio hat für mich, dass 2) so gelöst ist, dass es für die Anwender keinen Mehraufwand gibt.

**Comment by biscmar** [comment]
Neu kann im ersten Abschnitt "Spiel" eingestellt werden, ob eine Aufstellung erfasst werden soll oder nicht. Je nach dem werden andere Felder eingeblendet.
