### ISSUE TITLE
Subfoler "TCUconfig" im Code

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#16]
An diversen Orten im Code ist das Unterverzeichnis "TCUconfig" hart codiert. Allenfalls würde es Sinn machen, den Namen in config.js zu verlagern. Dann könnte das Tool auch in einem anderen Unterverzeichnis installiert werden.

**Comment by biscmar** [comment]
Die selbe Idee hatte ich auch :). Sollte jetzt überall den Wert aus dem config.js lesen.

**Comment by biscmar** [comment]
Müsste mit #17 erledigt sein.
