### ISSUE TITLE
Installation auf Webserver <> tugium

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#17]
Installiere ich die App auf einem anderen Webserver, dann muss ich in LocalSettings.php folgende Zeilen anpassen:
```
$fileLocation = getenv("DOCUMENT_ROOT") . '/' . 'TCUconfig/' . $_POST['OutputDirectory'] . '/system-config_' . $fileSuffix . '.txt';
...
$path = $_SERVER["HTTP_HOST"] . '/' . 'TCUconfig/' . $_POST['OutputDirectory'] . '/';
```

Jeweils das Directory "TCUconfig" muss hinzugefügt werden. Geben die Variablen "DOCUMENT_ROOT" und "HTTP_HOST"das Verzeichnis in jedem Fall mit?

Gleiche Problematik im File GameSettings.php.

**Comment by biscmar** [comment]
Nein der DOCUMENT_ROOT zeigt in der Regel immer auf das Root Verzeichnis des Webservers. Deshalb habe ich den Pfad zum output Verzeichnis in das Config File ausgelagert. Darin findest du die Variable outputDirectory. Wird das TCUconfig direkt ins Root installiert, reicht da "output" als Wert. Wenn das TCUconfig in ein Unterverzeichnis installiert wird, muss du dieses hier auch mit angeben.

Bei mir auf dem tugium Server steht da beispielsweise "TCUconfig/output" drin.

**Comment by patmu** [comment]
Funktioniert, Danke!
