### ISSUE TITLE
Game-Config: Spieldaten laden / Titel

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#35]
Spieldaten laden setzt den Wert "Liga-ID" auf "swiss unihockey".

Das Feld Titel wird mit dem Default gemäss config.js gesetzt.

**Comment by biscmar** [comment]
@patmu Was soll ich hier machen? Es gibt aktuell kein Feld "Liga-ID". Und das Feld Titel wird bereits aus dem config geladen.

**Comment by patmu** [comment]
ich glaube #33 und #34 müssten zuerst gemacht werden. dann sollte #35 klar sein.
