### ISSUE TITLE
Game-Config: Aufstellung erfassen "ja" -> Aufstellung/Starting 6 Topscorer

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#39]
Wenn Aufstellung erfassen auf ja steht.

Wenn in der Aufstellung der Topskorer vorkommt, soll dieser mit der Nummer 00 ins Config-File geschrieben werden (nicht mit seiner normalen Nummer). Das gilt auch für die Starting6.

Das kann auch erst beim Generieren des Config-Files gemacht werden und muss im GUI nicht visualisiert werden (ist ev. einfacher wenn der Topskorer später geändert wird.

**Comment by biscmar** [comment]
@patmu Verstehe ich das richtig, dass im Config der Topscorer nur noch mit der Nummer 00 vorkommt. Sowohl in der Aufstellung wie auch im Lineup?

**Comment by patmu** [comment]
gute frage... ich meinte er müsste eigentlich nicht doppelt drin sein. habe dies auch schnell getestet.

er kommt aber von der api mit einer normalen nummer und deshalb ist/war er doppelt abgelegt. man könnte ihn auch nur mit 00 ablegen.
