### ISSUE TITLE
Game-Config: Remove function "Thumbnail herunterladen"

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#40]
Auf dem neuen Hub benötigen wir das Thumbnail nicht mehr.

Der Button kann deaktiviert bzw. ausgeblendet werden. Ob der Code auch gelöscht wird, überlasse ich dir. Vielleicht haben wir wiedermal Bedarf für ein Thumbnail.

**Comment by biscmar** [comment]
Ich habe die Funktion entfernt. Wenn wir sie wieder mal brauchen, können wir die relevanten parts aus den älteren Versionen ziehen.
