### ISSUE TITLE
Auswahl Trikot-Farbe / Neutraler Wert fehlt

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#7]
Hier wäre es schön noch eine Box zu haben "keine Farbe". Zum Beispiel ein weisses Viereck mit einem roten Kreuz drin.

In diesem Fall wird der Parameter TeamColor einfach leergelassen und die Default-Farbe der Uhr automatisch gesetzt.

**Comment by patmu** [comment]
Genau. Wenn ich aber eine Farbe geklickt habe, habe ich keine Möglichkeit mehr die Selektion aufzuheben damit die Default-Farbe aus dem system-config angezeigt wird. Einzige Variante ist das Spiel neu zu laden, damit verliere ich aber auch die anderen bereits ausgefüllten Werte.

**Comment by biscmar** [comment]
Erledigt
