### ISSUE TITLE
Layout Heimteam / Auswärtsteam

### ISSUE THREAD

**Issue by patmu** [biscmar/TCUconfig#8]
Logischer wäre zuerst die Linien zu setzen und dann die Starting 6. Sonst weiss man gar nicht, was man mit Linie 1, 2, 3, 4 wählen kann.

Ebenfalls würde ich noch einen Titel für die Linien-Sektion analog Starting 6 setzen: "Aufstellung".

Mockup als Attachement:
![tcuconfig gui](https://user-images.githubusercontent.com/10456118/42832709-4ee20658-89f2-11e8-9db3-a6c6359cf26d.png)

**Comment by biscmar** [comment]
Erledigt
